// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5ZPwxO8ZWeSPHAM-bmufXgumws3KAyU',
    appId: '1:925433662628:web:2c3dfbe9bfe0de8abaaa31',
    messagingSenderId: '925433662628',
    projectId: 'activity012-fce62',
    authDomain: 'activity012-fce62.firebaseapp.com',
    storageBucket: 'activity012-fce62.appspot.com',
    measurementId: 'G-Y4E19XWEJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmmpNzhidmvWvihx6XC1i70TGupwZd1E8',
    appId: '1:925433662628:android:fe21d719fbd62796baaa31',
    messagingSenderId: '925433662628',
    projectId: 'activity012-fce62',
    storageBucket: 'activity012-fce62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoIXKshWhqGD4RewV8ilix06YJYI_Wr6E',
    appId: '1:925433662628:ios:d591a8c06783d784baaa31',
    messagingSenderId: '925433662628',
    projectId: 'activity012-fce62',
    storageBucket: 'activity012-fce62.appspot.com',
    iosBundleId: 'com.example.activiety012Invman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoIXKshWhqGD4RewV8ilix06YJYI_Wr6E',
    appId: '1:925433662628:ios:559fc02697275997baaa31',
    messagingSenderId: '925433662628',
    projectId: 'activity012-fce62',
    storageBucket: 'activity012-fce62.appspot.com',
    iosBundleId: 'com.example.activiety012Invman.RunnerTests',
  );
}
